[package]
name = "rust_refactor"
version = "0.1.1"
edition = "2018"
authors = ["Ben Santora <bensatlantik@gmail.com>"]
description = "A library for automated code refactoring in Rust."
https://github.com/Rust-Libraries-Binaries/rust_refactor.git
license = "MIT"

[dependencies]

[dev-dependencies]
